services:
  - ec2
  - rds
  - sqs
  - sns
  - lambda
  - s3
with_docs: true
with_clients: true
with_service_resources: true
with_paginators: true
with_waiters: true
package_name: boto3_type_annotations_essentials
module_name: boto3_type_annotations
version: 0.2.4
readme: README.md
license: LICENSE
