services: all
with_docs: true
with_clients: true
with_service_resources: false
with_paginators: false
with_waiters: false
package_name: mypy_boto3_clients
module_name: mypy_boto3
version: 0.1.0
readme: "../README.md"
license: "../LICENSE"
