services: all
with_docs: true
with_clients: true
with_service_resources: false
with_paginators: false
with_waiters: false
package_name: boto3_type_annotations_clients
module_name: boto3_type_annotations
version: 0.2.4
readme: README.md
license: LICENSE
