services:
  - s3
with_docs: true
with_clients: true
with_service_resources: true
with_paginators: true
with_waiters: true
package_name: mypy_boto3_essentials
module_name: mypy_boto3
version: 0.1.0
readme: "../README.md"
license: "../LICENSE"
