services: all
with_docs: false
with_clients: true
with_service_resources: true
with_paginators: true
with_waiters: true
package_name: boto3_type_annotations
module_name: boto3_type_annotations
version: 0.3.0
readme: "../README.md"
license: "../LICENSE"
